# Generated by Django 2.2.7 on 2020-01-26 13:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Строка в браузере')),
                ('image', models.ImageField(upload_to='brands', verbose_name='Изображение')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Строка в браузере')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CommonPageDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('Главная', 'Главная'), ('Каталог', 'Каталог'), ('Бренды', 'Бренды'), ('Распродажа', 'Распродажа'), ('Доставка', 'Доставка'), ('Контакты', 'Контакты')], default='Главная', max_length=14, verbose_name='Название страницы')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Описание страницы',
                'verbose_name_plural': 'Описания основных страниц',
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Контактные почтовые адреса (Email)',
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер вида +71234567890')),
                ('readable_phone', models.CharField(max_length=20, verbose_name='Этот же номер вида +7(123) 456-78-90')),
            ],
            options={
                'verbose_name': 'Контактный номер телефона',
                'verbose_name_plural': 'Контактные номера телефонов',
            },
        ),
        migrations.CreateModel(
            name='ShopPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides', verbose_name='Изображение слайда')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок слайда')),
                ('index', models.SmallIntegerField(verbose_name='Индекс')),
                ('description', models.CharField(max_length=128, verbose_name='Описание слайда')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Карусель',
            },
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=180, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Подписка на рассылку',
                'verbose_name_plural': 'Подписки на рассылку',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='products', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Процент скидки')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка?')),
                ('status', models.CharField(choices=[('В наличии', 'В наличии'), ('Ожидается', 'Ожидается'), ('Нет в наличии', 'Нет в наличии')], default='В наличии', max_length=14, verbose_name='Статус')),
                ('in_box', models.CharField(max_length=32, verbose_name='В коробке')),
                ('in_pallet', models.CharField(max_length=32, verbose_name='В паллете')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['pk'],
            },
        ),
    ]
