# Generated by Django 2.2.7 on 2020-03-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200226_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='keywords',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='commonpagedescription',
            name='keywords',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ключевые слова'),
        ),
    ]
